#!/bin/sh

# Redirect output to stderr.
exec 1>&2

# Check for unstaged changes.
staged_files=$(git diff --name-only --cached)

if [ -z "$staged_files" ]; then
  echo "No staged files. Skipping clang-format."
  exit 0
fi

# Run clang-format on the staged files.
for file in $staged_files; do
  if [ "${file##*.}" = "h" ] || [ "${file##*.}" = "cpp" ] || [ "${file##*.}" = "hpp" ] || [ "${file##*.}" = "cc" ]; then
    clang-format -style=file -i "$file" 
    git add "$file"
  fi
done

echo "All staged files formatted with clang-format."
