#!/bin/sh

echo "Setting up Git hooks..."

# Copy the pre-commit hook to the .git/hooks directory.
cp tools/pre-commit .git/hooks/pre-commit

# Make the pre-commit hook executable.
chmod +x .git/hooks/pre-commit

echo "Git hooks setup complete."
