name: ClangFormat

on:
  push:
    branches: [ main ]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install ClangFormat
      run: sudo apt-get update && sudo apt-get install -y clang-format

    - name: Format code
      run: find . -name "*.cpp" -o -name "*.hpp" -o -name "*.h" | xargs clang-format -i

    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "ClangFormat"
        git push